services:
  php_apache:
    build: 
      context: ./app/
      dockerfile: Dockerfile
    container_name: php_apache
    environment:
      - ABET_PRIVATE_DIR=/home/abet_private
      - DB_HOST=mysql
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_PASS}
      - SESSION_IDLE_TIMEOUT=1800
      - SESSION_ABSOLUTE_TIMEOUT=28800
      - SESSION_COOKIE_SAMESITE=Lax
    ports:
      - "8080:80"
    volumes:
      - ../src/public:/var/www/html
      - ../src/abet_private:/home/abet_private
    networks:
      - app_network
    depends_on:
      - mysql

  mysql:
    build: 
      context: ./mysql/
      dockerfile: Dockerfile
    container_name: mysql
    environment:
    # CHANGE THESE VALUES BEFORE DEPLOYING TO PRODUCTION
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ../src/abet_private:/home/abet_private
    networks:
      - app_network

networks:
  app_network:
    name: abet_tools_network
    driver: bridge
