services:
  php_apache:
    build: 
      context: ./app/
      dockerfile: Dockerfile
    container_name: php_apache
    environment:
      - ABET_PRIVATE_DIR=/home/abet_private
      - DB_HOST=localhost
      - DB_NAME=abet_tools_db
      - DB_USER=abet_user
      - DB_PASS=abet_password
      - SESSION_IDLE_TIMEOUT=1800
      - SESSION_ABSOLUTE_TIMEOUT=28800
      - SESSION_COOKIE_SAMESITE=Lax
    ports:
      - "8080:80"
    volumes:
      - ../src/public:/var/www/html
      - ../src/abet_private:/home/abet_private
    networks:
      - app_network
    depends_on:
      - mysql

  mysql:
    build: 
      context: ./mysql/
      dockerfile: Dockerfile
    container_name: mysql
    environment:
    # CHANGE THESE VALUES BEFORE DEPLOYING TO PRODUCTION
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: abet_tools_db
      MYSQL_USER: abet_user
      MYSQL_PASSWORD: abet_password
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ../src/abet_private:/home/abet_private

networks:
  app_network:
    name: abet_tools_network
    driver: bridge
