version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: php_server
    restart: always
    working_dir: /var/www
    environment:
      - ABET_PRIVATE_DIR=/home/abet_private
    volumes:
      - ../src/abet_private:/home/abet_private
      - ../src/public:/var/www/public
  nginx:
    image: nginx:1.29.5-alpine
    container_name: nginx_server
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src/abet_private:/home/abet_private
      - ../src/public:/var/www/public
      - ./nginx:/etc/nginx/conf.d